# Generated by Django 2.2.8 on 2021-02-09 06:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mp_city',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=30)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Mp_zone',
            fields=[
                ('zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mp_product',
            fields=[
                ('mpproduct_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=50)),
                ('lower_price', models.FloatField()),
                ('upper_price', models.FloatField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketprice.Mp_city')),
            ],
        ),
        migrations.AddField(
            model_name='mp_city',
            name='zone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketprice.Mp_zone'),
        ),
    ]
