# Generated by Django 2.2.8 on 2021-01-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_mo',
            field=models.IntegerField(),
        ),
    ]
