# Generated by Django 2.2.8 on 2021-01-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210119_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_mo',
            new_name='User_mo',
        ),
    ]
