# Generated by Django 2.2.8 on 2021-01-21 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=15)),
                ('brand_image', models.ImageField(upload_to='ecommerce/brands')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Category')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Top_product',
            fields=[
                ('topproduct_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Top_brand',
            fields=[
                ('topbrand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Brand')),
            ],
        ),
    ]
