# Generated by Django 2.2.8 on 2021-01-21 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_brand_top_brand_top_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Brand'),
        ),
    ]
