# Generated by Django 2.2.8 on 2021-02-28 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_tracker',
            fields=[
                ('order_tracker_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='items_json',
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.BigIntegerField(max_length=10),
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product')),
            ],
        ),
    ]
