# Generated by Django 2.2.8 on 2021-02-28 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20210228_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_tracker_id',
            field=models.ForeignKey(default=1234567893, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Order_tracker'),
            preserve_default=False,
        ),
    ]
