# Generated by Django 2.2.8 on 2021-02-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20210228_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(default='Cash on delivery', max_length=50),
        ),
    ]
