# Generated by Django 2.2.8 on 2021-03-09 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0014_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_review',
            fields=[
                ('product_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=1)),
                ('review_desc', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product')),
            ],
        ),
    ]
